### ISSUE TITLE
How to integrate Python and CANape

### ISSUE THREAD

**Issue by 1627583** [jedediahfrey/PyCANape#2]
Hello!

I installed your python module for using CANape API of python.
But I can't find any python files. just I can see __init__.py and _version.py.
Could you please guide for me how to use your python module?

Thank you in advanced!

**Comment by dapperfu** [comment]
The actual code is behind a firewall, I have updated the README to reflect this information.

If you are interested in seeing this developed and could lend a license for development I would be happy to contribute.

The fastest way may be to contact your local Vector representative and tell them you would like to see the Python module developed.
